apiVersion: v1  # 不要改动
kind: Plugin  # 不要改动
metadata:
  # author 和 name 唯一确定一个插件
  author: sheetung  # 插件作者，修改为你的名称
  name: versaBotPlugin  # 插件名称，修改为你的插件名称
  repository: 'https://github.com/sheetung/versaBotPlugin'  # 插件仓库地址，修改为你的插件 GitHub 仓库地址
  version: 0.1.0  # 插件版本，修改为你的插件版本
  description:  # 插件简介，修改为你的插件简介，支持多语言
    en_US: Quickly write plugins to implement personal small functions.
    zh_Hans: 快速编写实现个人小功能的插件
  label:  # 插件显示名称，支持多语言。在 WebUI 上会显示对应语言的 label
    en_US: versaBotPlugin
    zh_Hans: 多功能小插件集成
spec:
  # 插件配置（可选），可配置多项
  config:
    - name: NapCat_http  # 配置项名称
      label:  # 配置项显示名称，支持多语言
        en_US: NapCat_http host
        zh_Hans: NapCat_http 主机
      description:  # 配置项描述，支持多语言
        en_US: default (local) 127.0.0.1
        zh_Hans: 默认使用（即本地） 127.0.0.1
      type: string  # 配置项类型，支持 string, integer, float, boolean 等
      default: '127.0.0.1'  # 配置项默认值
      required: true  # 配置项是否必填
execution:
  python:
    path: main.py  # 插件主程序路径，必须与上方插件入口代码的文件名相同
    attr: MyPlugin  # 插件类名，必须与上方代码中声明的类名相同